<?php

/**
 * @file
 * Contains custom_contact.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function custom_contact_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the custom_contact module.
    case 'help.page.custom_contact':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('english version contact api') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function custom_contact_theme() {
  return [
    'custom_contact' => [
      'render element' => 'children',
    ],
  ];
}
